#! /usr/bin/env python
import os
import sys
import optparse
import gtk
import pygtk


#decide if we have been distributed in a deb or sitting in the source dir
if os.path.abspath(__file__) == "/usr/bin/snipplets":
    sys.path.append("/usr/share/snipplets")
    import snipplets
else:
    import src.snipplets as snipplets
__author__ = ("Daniel Woodhouse <wodemoneke@gmail.com>")
__version__ = "0.01"

parser = optparse.OptionParser(version="snipplets %s by %s" % (__version__, ', '.join(__author__)))
parser.add_option('--error-log', '-e', action="store_true", help="logs all stderr messages to ~/.snipplets/error.log") 

options, args = parser.parse_args()

snip = snipplets.RunSnipplets(author=__author__,
                   version=__version__, error_log=options.error_log)
gtk.main()

